// automatically generated by the FlatBuffers compiler, do not modify

module MyGame.Sample.Vec3;

import std.typecons;
import flatbuffers;

struct Vec3 {
	mixin Struct!Vec3;

	@property float x() { return _buffer.get!float(_pos + 0); }
	@property float y() { return _buffer.get!float(_pos + 4); }
	@property float z() { return _buffer.get!float(_pos + 8); }

	static uint createVec3(FlatBufferBuilder builder, float x, float y, float z) {
		builder.prep(4, 12);
		builder.put!float(z);
		builder.put!float(y);
		builder.put!float(x);
		return builder.offset();
	}
}

